server:
  port: 8081

spring:
  application:
    name: execution-service
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: Tak2268641!

  kafka:
    producer:
      bootstrap-servers: localhost:9092

    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 1000
      group-id: bitmoi

logging:
  level:
    root: info
    org.springframework.r2dbc: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
